#! /usr/local/bin/python2.7

from argparse import ArgumentParser
import subprocess
import shlex
import time
import os
# get dataset
def get_dataset_name(dataset, id):
    cmd = "zfs list -r -t snapshot -o name " + dataset
    args = shlex.split(cmd)
    result = subprocess.check_output(args)
    result = result.split("\n")
    result.pop()
    result.reverse()
    result.pop()
    return result[id-1]

# create
def create(dataset, rot_cnt):
    print("[snapshot] " + dataset + "@" + time.strftime("%Y-%m-%d_%H:%M:%S", time.localtime()))
    cmd = "sudo zfs snapshot " + dataset + "@" + time.strftime("%Y-%m-%d_%H:%M:%S", time.localtime())
    args = shlex.split(cmd)
    subprocess.check_call(args)

    # check snapshot counts
    cmd = "zfs list -r -t snapshot -o name " + dataset
    args = shlex.split(cmd)
    result = subprocess.check_output(args)
    result = result.split("\n")
    result.pop() # the last element is null str
    result.reverse()
    result.pop()

    if rot_cnt == None:
        rot_cnt = 20
    if len(result) > int(rot_cnt):
        print("- reach rotation count")
        for i in range(int(rot_cnt), len(result)):
            print("[delete] " + result[i])
            cmd = "zfs destroy " + result[i]
            args = shlex.split(cmd)
            subprocess.check_call(args)

# list
def list(dataset):
    # list all the snapshot
    # check_output: Run command with arguments and return its output as a byte string.
    if dataset == None:
        cmd = "zfs list -r -t snapshot -o name" # remove first line (Name)
    else:
        cmd = "zfs list -r -t snapshot -o name " + dataset
    args = shlex.split(cmd)
    result = subprocess.check_output(args)
    result = result.split("\n")
    result.pop()
    result.reverse()
    result.pop()
    print("ID".ljust(10) + "Dataset".ljust(20) + "Time".ljust(20))
    dataset_list = {}
    for line in result:
        if line != "":
            line = line.split("@")
            if line[0] not in dataset_list:
                dataset_list[line[0]] = 1
            else:
                dataset_list[line[0]] += 1
            print(str(dataset_list[line[0]]).ljust(10) + line[0].ljust(20) + line[1].ljust(20))

# delete
def delete(dataset, id=None):
    # get all the snapshot
    cmd = "zfs list -r -t snapshot -o name " + dataset
    args = shlex.split(cmd)
    result = subprocess.check_output(args)
    result = result.split("\n")
    result.pop()
    result.reverse()
    result.pop()

    if id == None: # delete all the snapshots of this dataset
        for snapshot in result:
            cmd = "sudo zfs destroy " + snapshot
            args = shlex.split(cmd)
            subprocess.check_call(args)
    else:
        snapshot = result[int(id)-1]
        cmd = "sudo zfs destroy " + snapshot
        args = shlex.split(cmd)
        subprocess.check_call(args)

# export
def export(dataset, id):
    if id == None:
        id = 1
    else:
        id = int(id)

    print("[export] " + dataset + " to ~/ftp_backup/export/")

    # export snapshot to file
    dataset_name = get_dataset_name(dataset, id)
    cmd = "sudo zfs send -R " + dataset_name + " > " + "/home/cysun/ftp_backup/export/" + dataset_name.replace("/", "_")
    dataset_name = dataset_name.replace("/", "_")
    dataset_name = "/home/cysun/ftp_backup/export/" + dataset_name
    p = subprocess.Popen(cmd, shell=True)
    os.waitpid(p.pid, 0)

    # compress
    cmd = "xz -z " + dataset_name
    args = shlex.split(cmd)
    subprocess.check_call(args)

    # encrypt
    cmd = "openssl aes256 -in " + dataset_name + ".xz -out " + dataset_name + ".xz.enc"
    args = shlex.split(cmd)
    subprocess.check_call(args)

    # remove reduntant .xz file
    cmd = "rm " + dataset_name + ".xz"
    args = shlex.split(cmd)
    subprocess.check_call(args)

    print("Successfully export as [" + dataset_name.split("/")[-1] + ".xz.enc]")

def _import(dataset, filename):
    print("[import] from file '" + filename + "'")
    path_filename = "/home/cysun/ftp_backup/export/" + filename
    # decrypt
    cmd = "openssl enc -aes256 -d -in " + path_filename + " -out " + path_filename[:-4]
    args = shlex.split(cmd)
    subprocess.check_call(args)

    # uncompress
    cmd = "xz -d " + path_filename[:-4]
    args = shlex.split(cmd)
    subprocess.check_call(args)

    # clean the previous snapshot
    delete(dataset)

    # import
    cmd = "sudo zfs receive -F " + dataset + " < " + path_filename[:-7]
    p = subprocess.Popen(cmd, shell=True)
    os.waitpid(p.pid, 0)
    print("Successfully import to '" + dataset + "'")

# parse command
parser = ArgumentParser(usage="./zbackup [[--list | --delete | --export] target-dataset [ID] | [--import] target-dataset filename | target-dataset [rotation count]]")

# zbackup [[--list | --delete | --export] target-dataset [ID] | [-- import] target-dataset filename | target dataset [rotation count]]

group = parser.add_mutually_exclusive_group()
group.add_argument("-l", "--list", help="List the snapshot created by zbackup (default=all)", action="store_true")
group.add_argument("-d", "--delete", help="Delete the specified snapshots created by zbackup (default=all)", action="store_true")
group.add_argument("-e", "--export", help="Export specified snapshot, which is 'dataset/to/backup@2018-10-12.xz.enc'", action="store_true")
group.add_argument("-i", "--_import", help="Load the snapshot to the dataset", action="store_true")

parser.add_argument("dataset", help="target-dataset", nargs="?")
parser.add_argument("id_cnt", help="ID/import-filename/rotation count", nargs="?")

args = parser.parse_args()

if args.list == True:
    list(args.dataset)
elif args.delete == True:
    delete(args.dataset, args.id_cnt)
elif args.export == True:
    export(args.dataset, args.id_cnt)
elif args._import == True:
    _import(args.dataset, args.id_cnt)
else: # create
    create(args.dataset, args.id_cnt)
